apiVersion: v1
kind: Service
metadata:
  name: skydrop-frontend-service
  namespace: skydrop
spec:
  type: NodePort
  selector:
    app: skydrop-frontend
  ports:
    - port: 6001
      targetPort: 6001
      nodePort: 32001
