apiVersion: apps/v1
kind: Deployment
metadata:
  name: skydrop-frontend
  namespace: skydrop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: skydrop-frontend
  template:
    metadata:
      labels:
        app: skydrop-frontend
    spec:
      containers:
        - name: frontend
          image: skydrop-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6001
