apiVersion: v1
kind: Secret
metadata:
  name: server-secret
  namespace: skydrop
type: Opaque
stringData:
  PORT: "3001"
  MONGO_URL: "mongodb://skydrop:ulysseetchatgptnefontq1@mongo-service.skydrop.svc.cluster.local:27017/skydrop?authSource=admin&replicaSet=rs0"
  JWT_SECRET: "fallback-secret-token-for-dev"
  SALT_ROUNDS: "10"
