apiVersion: v1
kind: Service
metadata:
  name: skydrop-server-service
  namespace: skydrop
spec:
  selector:
    app: skydrop-server
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: ClusterIP
