apiVersion: batch/v1
kind: Job
metadata:
  name: mongo-init
  namespace: skydrop
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
      - name: mongo-init
        image: mongo:4.4
        command:
          - mongo
          - --host
          - mongo-0.mongo-headless.skydrop.svc.cluster.local
          - --eval
          - |
            rs.initiate({
              _id: "rs0",
              members: [
                { _id: 0, host: "mongo-0.mongo-headless.skydrop.svc.cluster.local:27017" },
                { _id: 1, host: "mongo-1.mongo-headless.skydrop.svc.cluster.local:27017" },
                { _id: 2, host: "mongo-2.mongo-headless.skydrop.svc.cluster.local:27017" }
              ]
            })
