apiVersion: v1
kind: Service
metadata:
  name: skydrop-web-service
  namespace: skydrop
spec:
  type: NodePort
  selector:
    app: skydrop-frontend
  ports:
    - port: 3004
      targetPort: 3004
      nodePort: 30020
